FORMAT: 1A
HOST: https://locahost/

# TOOLS

Tools API integration services definition

| Version     | Change description    | Date |
| ----------- | --------------------- |----------|
| 1.0.0 | First approach to business needs | 2021-12-08 |

# Group Authentication

In this section are all the services related to authentication 

### Constraints

- VPN Required: NO
- Private Service: YES

## Get Token [/auth/login/]

### Get token [GET]

##### form-data
| Key    | Value                     | Type   | Length | Mandatory |
|--------------|---------------------------------|--------|--------|-----------|
| username | email registered on the platform | Text |        | Y         |
| password    | password registered on the platform | Text |        | Y         |

##### Response 200
| Attribute   | Description          | Type      | Length  | Mandatory   |
| ----------- | -------------------- | --------- | ------- | ----------- |
| access       | access token to the other services | String    |         | Y           |
| refresh       | refresh token | String    |         | Y           |

##### Response 401
| Attribute   | Error message |
| ----------- | ------------------------------------------------------- |
| detail | No active account found with the given credentials|


+ Response 200 (application/json)

        {
            "access": "eyJ1c2VyX2lkIjoxfQ.X40jZg.fyFu4D-icSRcepC4TwQc-WfYdZg",
            "refresh": "eyJ1c2VyX2lkIjoxfQ.YXg1bQ.H6LM3aWEbpo99J5O3UVvI6-pib8"
        }
        

+ Response 401 (application/json)

        {
            "detail": "No active account found with the given credentials"
        }

